### ISSUE TITLE
Does not install on 3.6 version of blender

### ISSUE THREAD

**Issue by Devon0209** [zonkosoft/BlendyPose#14]
![image](https://github.com/zonkypop/BlendyPose/assets/69379861/a4970f9f-08c3-4775-b25f-611cd8713376)

Heres the error in the Info Log:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Blender_Launcher_v1.14.1_Windows_x64\stable\blender-3.6.4+stable.21bfc5e7fe3f\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\PosePipe-main\__init__.py", line 30, in <module>
    from PosePipe.core.Setups import *
ModuleNotFoundError: No module named 'PosePipe'

**Comment by j2l** [comment]
Same on Blender 2.93
